//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KarYab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADRESS
    {
        public ADRESS()
        {
            this.OWNERSADRESES = new HashSet<OWNERSADRES>();
        }
    
        public long ID { get; set; }
        public string ADRESS1 { get; set; }
    
        public virtual ICollection<OWNERSADRES> OWNERSADRESES { get; set; }
    }
}
