//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KarYab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CELLPHONE
    {
        public CELLPHONE()
        {
            this.OWNERSCELLPHONES = new HashSet<OWNERSCELLPHONE>();
        }
    
        public long ID { get; set; }
        public long CELLPHONENUMBER { get; set; }
    
        public virtual ICollection<OWNERSCELLPHONE> OWNERSCELLPHONES { get; set; }
    }
}
