//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KarYab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRACTTYPE
    {
        public CONTRACTTYPE()
        {
            this.OWNERSCONTRACTTYPES = new HashSet<OWNERSCONTRACTTYPE>();
        }
    
        public long ID { get; set; }
        public string CONTRACTTYPE1 { get; set; }
    
        public virtual ICollection<OWNERSCONTRACTTYPE> OWNERSCONTRACTTYPES { get; set; }
    }
}
