//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KarYab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDUCATON
    {
        public EDUCATON()
        {
            this.OWNERSEDUCATIONS = new HashSet<OWNERSEDUCATION>();
        }
    
        public long ID { get; set; }
        public string EDUCATIONLOCATION { get; set; }
        public string EDUCATIONBRANCH { get; set; }
        public string EDUCATIONDIPLOMA { get; set; }
        public byte EDUCATIONDURATION { get; set; }
        public short FINALGRADE { get; set; }
    
        public virtual ICollection<OWNERSEDUCATION> OWNERSEDUCATIONS { get; set; }
    }
}
