//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KarYab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXPERIENCE
    {
        public EXPERIENCE()
        {
            this.OWNERSEXPERIENCES = new HashSet<OWNERSEXPERIENCE>();
        }
    
        public long ID { get; set; }
        public string EXPERIENCELOCATOION { get; set; }
        public short EXPERIENCEDURATION { get; set; }
    
        public virtual ICollection<OWNERSEXPERIENCE> OWNERSEXPERIENCES { get; set; }
    }
}
