//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KarYab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAILADRESS
    {
        public MAILADRESS()
        {
            this.OWNERSMAILS = new HashSet<OWNERSMAIL>();
        }
    
        public long ID { get; set; }
        public string MAILADRESS1 { get; set; }
    
        public virtual ICollection<OWNERSMAIL> OWNERSMAILS { get; set; }
    }
}
