//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KarYab.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KARYABDBEntities : DbContext
    {
        public KARYABDBEntities()
            : base("name=KARYABDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADRESS> ADRESSES { get; set; }
        public virtual DbSet<CELLPHONE> CELLPHONES { get; set; }
        public virtual DbSet<CONTRACT> CONTRACTS { get; set; }
        public virtual DbSet<CONTRACTTYPE> CONTRACTTYPES { get; set; }
        public virtual DbSet<EDUCATON> EDUCATONS { get; set; }
        public virtual DbSet<EXPERIENCE> EXPERIENCES { get; set; }
        public virtual DbSet<HUMAN> HUMen { get; set; }
        public virtual DbSet<IMAGE> IMAGES { get; set; }
        public virtual DbSet<MAILADRESS> MAILADRESSES { get; set; }
        public virtual DbSet<OWNERSADRES> OWNERSADRESES { get; set; }
        public virtual DbSet<OWNERSCELLPHONE> OWNERSCELLPHONES { get; set; }
        public virtual DbSet<OWNERSCONTRACT> OWNERSCONTRACTS { get; set; }
        public virtual DbSet<OWNERSCONTRACTTYPE> OWNERSCONTRACTTYPES { get; set; }
        public virtual DbSet<OWNERSEDUCATION> OWNERSEDUCATIONS { get; set; }
        public virtual DbSet<OWNERSEXPERIENCE> OWNERSEXPERIENCES { get; set; }
        public virtual DbSet<OWNERSMAIL> OWNERSMAILS { get; set; }
        public virtual DbSet<OWNERSPHO> OWNERSPHOES { get; set; }
        public virtual DbSet<OWNERSPOINT> OWNERSPOINTS { get; set; }
        public virtual DbSet<OWNERSSALARy> OWNERSSALARIES { get; set; }
        public virtual DbSet<OWNERSSKILL> OWNERSSKILLS { get; set; }
        public virtual DbSet<PASSWORD> PASSWORDS { get; set; }
        public virtual DbSet<PHONE> PHONES { get; set; }
        public virtual DbSet<POINT> POINTS { get; set; }
        public virtual DbSet<SALARy> SALARIES { get; set; }
        public virtual DbSet<SKILL> SKILLS { get; set; }
    }
}
