//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KarYab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PASSWORD
    {
        public long ID { get; set; }
        public long HUMANID { get; set; }
        public string PASSWORD1 { get; set; }
        public string CONFIRMPASSWORD { get; set; }
        public string EMAIL { get; set; }
        public string ANSWER { get; set; }
    
        public virtual HUMAN HUMAN { get; set; }
    }
}
