//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KarYab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONE
    {
        public PHONE()
        {
            this.OWNERSPHOES = new HashSet<OWNERSPHO>();
        }
    
        public long ID { get; set; }
        public long PHONENUMBER { get; set; }
    
        public virtual ICollection<OWNERSPHO> OWNERSPHOES { get; set; }
    }
}
