//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KarYab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALARy
    {
        public SALARy()
        {
            this.OWNERSSALARIES = new HashSet<OWNERSSALARy>();
        }
    
        public long ID { get; set; }
        public string SALARYAMOUNT { get; set; }
    
        public virtual ICollection<OWNERSSALARy> OWNERSSALARIES { get; set; }
    }
}
