//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KarYab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SKILL
    {
        public SKILL()
        {
            this.OWNERSSKILLS = new HashSet<OWNERSSKILL>();
        }
    
        public long ID { get; set; }
        public string SKILLNAME { get; set; }
        public Nullable<byte> SKILLEFFICENYID { get; set; }
        public string SKILLDESCRIPTION { get; set; }
    
        public virtual ICollection<OWNERSSKILL> OWNERSSKILLS { get; set; }
    }
}
